services:
  tour_management_db:
    container_name: tour_management_db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tour_management
    ports:
      - 3306:3306
    volumes:
      - ./postgres-data:/var/lib/ie402_mysql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 3

  # backend:
  #   container_name: backend
  #   image: duong0907/backend:1.0.0
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     ACCESS_TOKEN_SECRET: 6194d1488263cf95ac02f792b3214c516c21361128a33c6d8e117054cf1006949821aa18d7169399f0aa030cda2564683588c043b3b9087a892de8047fa22197
  #     ACCESS_TOKEN_EXPIRES_IN: 1h
  #     DB_HOST=tour_management_db
  #     DB_USER: postgres
  #     DB_PASSWORD: secret
  #     DB: tour_management
  #     DB_DIALECT: mysql
  #     DB_PORT: 3306
  #   ports: 
  #     - 8080:8080
  #   depends_on:
  #     pg_db:
  #       condition: service_healthy


# Uncommnet to enable full backend